
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. Create Tables
-- ==========================================

-- 1.1 Jobs Table
create table if not exists public.jobs (
  id uuid primary key default uuid_generate_v4(),
  "jobRunningId" text not null,
  "repairOrderNumber" text,
  "dateReceived" date not null,
  "jobType" text not null,
  department text not null,
  "assetId" text,
  "itemDescription" text not null,
  "damageDescription" text,
  "repairGroup" text not null,
  status text not null,
  "dueDate" date,
  "finishedDate" date,
  "technicianIds" jsonb default '[]'::jsonb,
  costs jsonb default '[]'::jsonb,
  evaluation jsonb,
  assessment text,
  "lastUpdated" timestamp with time zone default timezone('utc'::text, now()),
  "pmPlanId" text, -- Link to PM Plan
  attachments jsonb default '[]'::jsonb -- Files
);

-- Migration for attachments
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'jobs' and column_name = 'attachments') then
    alter table public.jobs add column attachments jsonb default '[]'::jsonb;
  end if;
end $$;

-- 1.2 Technicians Table
create table if not exists public.technicians (
  id text primary key,
  "firstName" text not null,
  "nickName" text not null,
  "empId" text,
  position text not null,
  category text,
  schedule jsonb default '{}'::jsonb
);

-- 1.3 App Settings Table
create table if not exists public.app_settings (
  id int primary key,
  departments jsonb,
  technician_positions jsonb,
  technician_categories jsonb,
  expense_categories jsonb,
  companies jsonb,
  theme_color text,
  id_mappings jsonb,
  pm_types jsonb, -- New Column for Asset Types
  budget_categories jsonb, -- New Column for Budget Categories
  repair_groups jsonb, -- New Column for Repair Groups (Dynamic)
  divisions jsonb, -- New: หน่วยงาน (MTN, MOT)
  factory_groups jsonb, -- New: กลุ่มโรงงาน (Factory 101, 105)
  department_group_mappings jsonb, -- New: จับคู่แผนกกับกลุ่มโรงงาน
  division_mappings jsonb -- New: จับคู่หมวดงานกับหน่วยงาน (MTN/MOT)
);

-- IMPORTANT MIGRATION: Run this to add columns if tables already exist
do $$
begin
  -- Add id_mappings if missing
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'id_mappings') then
    alter table public.app_settings add column id_mappings jsonb;
  end if;
  
  -- Add pm_types if missing (For Asset Types)
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'pm_types') then
    alter table public.app_settings add column pm_types jsonb;
  end if;

  -- Add budget_categories if missing
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'budget_categories') then
    alter table public.app_settings add column budget_categories jsonb;
  end if;

  -- Add repair_groups if missing
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'repair_groups') then
    alter table public.app_settings add column repair_groups jsonb;
  end if;

  -- NEW: Add divisions
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'divisions') then
    alter table public.app_settings add column divisions jsonb default '[{"name": "ซ่อมบำรุง", "code": "MTN"}, {"name": "ยานยนต์", "code": "MOT"}]'::jsonb;
  end if;

  -- NEW: Add factory_groups
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'factory_groups') then
    alter table public.app_settings add column factory_groups jsonb default '["โรงงาน 101", "โรงงาน 106"]'::jsonb;
  end if;

  -- NEW: Add department_group_mappings
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'department_group_mappings') then
    alter table public.app_settings add column department_group_mappings jsonb default '{}'::jsonb;
  end if;

  -- NEW: Add division_mappings
  if not exists (select 1 from information_schema.columns where table_name = 'app_settings' and column_name = 'division_mappings') then
    alter table public.app_settings add column division_mappings jsonb default '{"ไฟฟ้า": "MTN", "ประปา": "MTN", "เครื่องปรับอากาศ (แอร์)": "MTN", "ซ่อมทั่วไป/เซอร์วิส": "MTN", "ก่อสร้าง/โครงสร้าง": "MTN", "ยานยนต์": "MOT"}'::jsonb;
  end if;

  -- Add pmPlanId to jobs if missing
  if not exists (select 1 from information_schema.columns where table_name = 'jobs' and column_name = 'pmPlanId') then
    alter table public.jobs add column "pmPlanId" text;
  end if;
end $$;

-- 1.4 User Roles Table
create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null check (role in ('SYSTEM_ADMIN', 'DEPT_ADMIN', 'HEAD', 'TECHNICIAN'))
);

-- 1.5 PM Plans Table (New Table)
create table if not exists public.pm_plans (
  id text primary key,
  name text not null,
  department text not null,
  frequency int not null,
  description text,
  "assetId" text,
  "nextDueDate" date,
  type text, -- Asset Type
  "lastDoneDate" date,
  "planType" text -- 'S', 'P', 'EP', 'C'
);

-- Migration for PM Plans (in case table existed but columns were missing)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'pm_plans' and column_name = 'type') then
    alter table public.pm_plans add column type text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'pm_plans' and column_name = 'lastDoneDate') then
    alter table public.pm_plans add column "lastDoneDate" date;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'pm_plans' and column_name = 'planType') then
    alter table public.pm_plans add column "planType" text;
  end if;
end $$;

-- 1.6 Factory Holidays Table
create table if not exists public.factory_holidays (
  id text primary key,
  date date not null,
  name text not null
);

-- 1.7 Budgets Table
create table if not exists public.budgets (
  id text primary key,
  year int not null,
  category text not null,
  "itemCode" text, -- New Column
  name text not null,
  "totalBudget" numeric not null default 0,
  "monthlyPlan" jsonb default '[]'::jsonb,
  "monthlyActual" jsonb default '[]'::jsonb
);

-- Migration for itemCode
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'budgets' and column_name = 'itemCode') then
    alter table public.budgets add column "itemCode" text;
  end if;
end $$;

-- 1.8 Daily Expenses Table (NEW)
create table if not exists public.daily_expenses (
  id text primary key,
  year int not null,
  month int not null,
  division text not null,
  "budgetId" text not null,
  "budgetCategory" text,
  "budgetName" text,
  "itemName" text not null,
  "productCode" text, -- New Column
  "pricePerUnit" numeric not null default 0,
  "quantityDays" jsonb default '[]'::jsonb,
  "totalQuantity" numeric not null default 0,
  "totalPrice" numeric not null default 0,
  "standardItemId" text -- New Column: Link to Standard Items
);

-- Migration for productCode
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'daily_expenses' and column_name = 'productCode') then
    alter table public.daily_expenses add column "productCode" text;
  end if;
  -- Migration for standardItemId
  if not exists (select 1 from information_schema.columns where table_name = 'daily_expenses' and column_name = 'standardItemId') then
    alter table public.daily_expenses add column "standardItemId" text;
  end if;
end $$;

-- 1.9 Standard Items Table (NEW) - For Persistent Rows (Template)
create table if not exists public.standard_items (
  id text primary key,
  code text,
  name text not null,
  unit text,
  "pricePerUnit" numeric not null default 0,
  "budgetId" text not null,
  "budgetCategory" text,
  "budgetName" text,
  division text
);

-- ==========================================
-- 2. Indexes (NEW) - Optimizing Performance
-- ==========================================

-- Index for querying Daily Expenses by Period and Division
create index if not exists idx_daily_expenses_query on public.daily_expenses (year, month, division);

-- Index for Standard Items
create index if not exists idx_daily_expenses_standard_item on public.daily_expenses ("standardItemId");

-- Index for fetching Standard Items by Division
create index if not exists idx_standard_items_division on public.standard_items (division);

-- Index for Budget lookups by Year
create index if not exists idx_budgets_year on public.budgets (year);

-- ==========================================
-- 3. Security & RLS
-- ==========================================

-- Enable RLS
alter table public.jobs enable row level security;
alter table public.technicians enable row level security;
alter table public.app_settings enable row level security;
alter table public.user_roles enable row level security;
alter table public.pm_plans enable row level security;
alter table public.factory_holidays enable row level security;
alter table public.budgets enable row level security;
alter table public.daily_expenses enable row level security;
alter table public.standard_items enable row level security;

-- Create Policies (Idempotent - Safe to run multiple times)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'jobs' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.jobs for all using (true) with check (true);
  end if;
  
  if not exists (select 1 from pg_policies where tablename = 'technicians' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.technicians for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'app_settings' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.app_settings for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'user_roles' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.user_roles for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'pm_plans' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.pm_plans for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'factory_holidays' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.factory_holidays for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'budgets' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.budgets for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'daily_expenses' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.daily_expenses for all using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where tablename = 'standard_items' and policyname = 'Enable all access for all users') then
    create policy "Enable all access for all users" on public.standard_items for all using (true) with check (true);
  end if;
end $$;

-- ==========================================
-- 4. ENABLE REALTIME REPLICATION (Safe Mode)
-- ==========================================
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'jobs') then
    alter publication supabase_realtime add table jobs;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'pm_plans') then
    alter publication supabase_realtime add table pm_plans;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'technicians') then
    alter publication supabase_realtime add table technicians;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'app_settings') then
    alter publication supabase_realtime add table app_settings;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'user_roles') then
    alter publication supabase_realtime add table user_roles;
  end if;
end $$;
